const{test,expect}=require('@playwright/test')
const exp = require('constants')
test("Selectorsd demo",async({page})=>{
   await page.goto('https://www.saucedemo.com/v1/')
   //await page.pause()
   await page.locator('#user-name').fill('standard_user')
   await page.locator('#password').fill('secret_sauce')
   await page.locator('#login-button').click()
   await expect(page.locator('#item_4_title_link')).toHaveText('Sauce Labs Backpack')
   await expect(page.locator('.product_label')).toHaveText('Products')
   await expect(page).toHaveURL('https://www.saucedemo.com/v1/inventory.html')
   await page.waitForTimeout(4000)
   //await expect(page.locator('._product_label')).toHaveText('Products')
   //await expect(page.locator('app_logo')).toHaveText('')
    
    //await expect(page.locator('.product_label')).toHaveText('Products')

   //await page.locator('')
}) 
test.only("Selector invalid",async({page})=>{
    await page.goto('https://www.saucedemo.com/v1/')
    await page.locator('#user-name').fill('standard_user1')
    await page.locator('#password').fill('santa')
    await page.locator('#login-button').click()
    await expect(page.locator('img[src="img/Login_Bot_graphic.png"]')).toBeVisible()
    //await expect(page.locator('#login_credentials')).toHaveText('Accepted usernames are:')
    //await expect(page.locator('img["src=img/SwagLabs_logo.png"]')).toBeVisible()
    //await expect(page.locator('.error-button')).toHaveText('Epic sadface: Username and password do not match any user in this service')
    await page.waitForTimeout(4000)
})